### PR TITLE
[v3io-webapi,v3iod] add v3io_config file for v3io-webapi and v3iod

### PR DESCRIPTION
**Pull request by alexbondar92**
add v3io_config file for v3io-webapi and v3iod

### CODE REVIEW

**Review by assaf758 — APPROVED** [review]

**Comment by alexbondar92** [comment]
passed smoke,
run_naipi/development - #105609 unknown_build SUCCESS after 1 hr 0 min (https://jenkins-prod.iguazeng.com/job/run_naipi/job/development/105609/)

**Comment by Hedingber** [comment]
@alexbondar92 @assaf758 
Note that you merged this PR but didn't release - it means that a new build doesn't take your new helm chart so... 
I see that @omesser did release on the day you merged in the evening so now "it's in" but surely after that run naipi mentioned

**Comment by alexbondar92** [comment]
@Hedingber the naipi mentioned, ran before the pr
I injected the charts and run naipi for testing

**Comment by assaf758** [comment]
@Hedingber thanks for letting us know, personally I was not aware of a 'release' step - where do we release a new helm?

**Pull request merged**
